#!/usr/bin/ruby

sn =ARGV[0].upcase();


print "#ifndef " + sn + "_H\n";
print "#define " + sn + "_H\n";
print "/* File automagically generated by rb2h.rb. Do not edit! */\n";

print "static const char *rubySysInitScript[] = {\n";

def parseLine(line)
a = Regexp.compile('\\\\');
  m = /^\s*#___INCLUDE (.*)$/.match(line);
  if m != nil
    open(m[1]) { |line|
      parseLine(line);
    }
  else
    # ok, someone please explain my why this works....
    line.gsub!(a, '\\\\\\\\');
    line.gsub!(/\n/, "\\n");
    line.gsub!(/"/, "\\\"");
    puts '"' + line + '",' +"\n";
  end
end

STDIN.each { |line|
  parseLine(line);
}

print "0 };\n"
print "#endif\n";
